<?php
  function dnamodule_menu() {
    $items['dna-match'] = array(
      'title' => 'DNA Complement Generator',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('dnapair_form'),
      'access callback' => TRUE,
      'type' => MENU_NORMAL_ITEM,
    );
    $items['results'] = array(
      'title' => 'DNA Pair Results',
      'page callback' => 'dna_results',
      'access callback' => TRUE,
      'type' => MENU_CALLBACK,
    );
    return $items;
  }

  function dnapair_form() {
    $form['input'] = array(
      '#title' => 'Find the complement to any DNA string. Enter a string of DNA below:',
      '#type' => 'textfield',
      '#element_validate' => array('element_validate_dna'),
      '#required' => TRUE,
    );
    $form['submit'] = array(
      '#type' => 'submit',
      '#value' => t('Find my complement!'),
    );
    return $form;
  }

  function element_validate_dna($element) {
    $input = strtoupper($element['#value']);
    $_SESSION['input'] = $input;
    $unaccepted = ['B', 'D', 'E', 'F', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'U', 'V', 'W', 'X', 'Y', 'Z', '1', '2', '3', '4', '5', '6', '7', '8', '9', '0', '"', "'", '.', ',', '!', "?", "(", ")", "-", ' '];
    foreach($unaccepted as $badletter) {
      if (strpos($input, $badletter) !== FALSE) {
        form_error($element, t('Please enter a valid DNA string, with only the letters G, A, T, and C in sequence.'));
      }
    }
  }

  function dnapair_form_submit(&$form, &$form_state) {
    $dnastring = strtoupper($form_state['values']['input']);
    $dna_array = str_split($dnastring);
    $output = array();
    for ($i = 0; $i < count($dna_array); $i++) {
      if ($dna_array[$i] == 'A') {
        array_push($output, 'T');
      } else if ($dna_array[$i] == 'C') {
        array_push($output, 'G');
      } else if ($dna_array[$i] == 'G') {
        array_push($output, 'C');
      } else if ($dna_array[$i] == 'T') {
        array_push($output, 'A');
      }
    }
    $_SESSION['output'] = implode($output);
    drupal_goto('results');
  }

  function dna_results() {
    return '<p>Success! You submitted: ' . $_SESSION['input'] . ' and the complement DNA string output for that is: ' . $_SESSION['output'] . '</p>';
  }
